// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "f5cc3122-daba-4d03-ae08-c93fb74a9f36");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1681556279);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1681556201);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1681556199);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{3052f1b1-4c52-4301-af1f-0d1f7e99e4ca}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1681556249);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{af9f41d1-6ffa-4884-b326-bd041931dcfa}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1681556211972");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1681557993972");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230406031538");
user_pref("browser.startup.homepage_override.mstone", "102.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1681556264);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1681556288941");
user_pref("distribution.iniFile.exists.appversion", "102.10.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9e3cd8a28df947e990e3fd8880171090");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230406031538");
user_pref("extensions.lastAppVersion", "102.10.0");
user_pref("extensions.lastPlatformVersion", "102.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"fbfe1eb3-16ac-44ad-b3d1-70321ca3f7d7\",\"formautofill@mozilla.org\":\"e4d307e2-a202-43de-bf1f-18cce68f79d1\",\"pictureinpicture@mozilla.org\":\"36e015cb-1d4c-4a2b-b900-4bfee152c3d7\",\"screenshots@mozilla.org\":\"84516f85-b7cb-4123-a3fc-cd5074c97909\",\"webcompat-reporter@mozilla.org\":\"f6e39a1b-fcf9-4e03-b68f-c365db4599f1\",\"webcompat@mozilla.org\":\"e64b9190-9a97-494e-81a0-e02b7b2a8345\",\"default-theme@mozilla.org\":\"57ce4f26-8067-4326-b5ef-78e7beb22df6\",\"addons-search-detection@mozilla.com\":\"56b590de-c0ba-4ef5-9c06-7e1acd3d8c4f\",\"google@search.mozilla.org\":\"cc985df6-921d-4ab2-a910-d0062eb48dcb\",\"amazondotcom@search.mozilla.org\":\"02fb6a93-bcf1-4aeb-98a8-ac5d95fd36d1\",\"wikipedia@search.mozilla.org\":\"fd16c84a-0905-4240-b3e4-332e40c4ea46\",\"bing@search.mozilla.org\":\"837c9232-bd6d-4eb1-aba9-d90fd391aac3\",\"ddg@search.mozilla.org\":\"8b784710-b27d-4a3b-b01a-d0f1f24d9a9e\",\"uBlock0@raymondhill.net\":\"f7532bba-a0b6-4b98-aa6b-e736439c0755\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1681556289);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1681556119);
user_pref("toolkit.telemetry.cachedClientID", "1cbbb3f2-6c85-4bb1-bf3d-cc1b8354ea9f");
user_pref("toolkit.telemetry.previousBuildID", "20230406031538");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
