#!/bin/sh

export LC_ALL=en_US.UTF-8
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_FONT_DPI=96
export GTK2_RC_FILES="/usr/share/nomadbsd-setup/gtkrc-2.0"
wallpaper="/usr/share/nomadbsd-setup/background.jpg"
xrdb /usr/share/nomadbsd-setup/Xresources

(xev -root -event randr | awk -v bg="${wallpaper}" '
	BEGIN {
		cmd = sprintf("feh --no-fehbg --bg-fill '%s'", bg);
		system(cmd);
	}
	/RRScreenChangeNotify/ {
		system(cmd);
	}
')&

# Use sysmouse if there is a problem with the touchpad
/usr/bin/tpquirk

# Enable tapping on touchpad
/usr/bin/enable_tapping

/usr/bin/nomadbsd-setup-gui&
exec openbox-session

