#!/bin/sh

export LC_ALL=en_US.UTF-8
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
export QT_QPA_PLATFORMTHEME=gtk2
export GTK2_RC_FILES="/usr/share/nomadbsd-setup/gtkrc-2.0"
feh --no-fehbg --bg-fill /usr/share/nomadbsd-setup/background.png

# Use sysmouse if there is a problem with the touchpad
if grep 'TouchPad.*:.*kernel bug' /var/log/Xorg.0.log; then
	sysctl kern.evdev.rcpt_mask=9
fi

/usr/bin/nomadbsd-setup-gui&
exec openbox-session

