#!/bin/sh -
#
# Copyright (c) 2020  The NomadBSD Project
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# PROVIDE: brightness
# REQUIRE: FILESYSTEMS kld
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="brightness"
desc="Save and restore brightness values"
rcvar="brightness_enable"
stop_cmd="brightness_stop"
start_cmd="brightness_start"
reload_cmd="brightness_start"
extra_commands="reload"
path_intel_backlight="/usr/local/bin/intel_backlight"

load_rc_config $name
: ${brightness_enable:="YES"}

brightness_start()
{
	[ ! -f /var/db/brightness ] && return
	eval $(cat /var/db/brightness)
}

brightness_stop()
{
	local dev
	if [ -x "${path_intel_backlight}" ]; then
		brightness=$(${path_intel_backlight} | awk -F'[ %]+' '{
			if ($4 > 0)
				print($4);
		}')
		if [ -n "${brightness}" ]; then
			echo "${path_intel_backlight} ${brightness}" > /var/db/brightness
			return
		fi
	fi
	brightness=$(sysctl -in hw.acpi.video.lcd0.brightness)
	if [ -n "${brightness}" ]; then
		echo "sysctl -i hw.acpi.video.lcd0.brightness=${brightness}" > /var/db/brightness
	fi
}

run_rc_command "$1"
