#!/bin/sh
#
# PROVIDE: gsched
# REQUIRE: LOGIN
#
# Add the following line to /etc/rc.conf to enable gsched:
#
# gsched_enable="YES"

. /etc/rc.subr

name=gsched
rcvar=gsched_enable
start_cmd=gsched_start
required_modules="geom_sched gsched_rr"
load_rc_config ${name}

: ${gsched_enable:="NO"}

gsched_start()
{
	rootdev=`glabel status | grep nomadroot | awk -F" " '{ print $3 }'`
	if [ -z "${rootdev}" ]; then
		echo "Error: Couldn't find root device!"
		exit 1
	fi
	dev=`echo ${rootdev} | sed -E 's/(.*)p[0-9]/\1/'`
	gsched insert ${dev}
}
run_rc_command "$1"
