#!/bin/sh
#
# PROVIDE: mount_uzip
# BEFORE: ldconfig NETWORKING
# REQUIRE: FILESYSTEMS

. /etc/rc.subr 
name=mount_uzip
start_cmd=do_mount_uzip

required_modules="geom_uzip"

do_mount_uzip()
{
	echo "Mounting uzip. Please wait ..."
	mdmfs -P -F /uzip/usr.local.uzip -oro md.uzip /usr/local

	# Create and mount a writeable directory to /usr/local using
	# unionfs, so users can install packages.
	if [ ! -d /home/pkgs ]; then
		mkdir /home/pkgs
	fi
	mount -t unionfs -o rw,noatime /home/pkgs /usr/local
}

load_rc_config $name
run_rc_command "$1"

