#!/bin/sh
#
# PROVIDE: mount_uzip
# BEFORE: ldconfig NETWORKING
# REQUIRE: FILESYSTEMS

. /etc/rc.subr 
name=mount_uzip
start_cmd=do_mount_uzip

required_modules="geom_uzip"
spinner_pid=-1

#
# Make sure to kill the spinner if the script receives a signal
#
kill_spinner() {
	[ ${spinner_pid} -gt -1 ] && kill -KILL ${spinner_pid}
	exit 1
}

do_mount_uzip()
{
	#
	# Create a spinner to indicate progress
	#
	{
		spinner="| / - \\ | / - \\"
		while [ true ]; do
			for i in ${spinner}; do
				printf "\r"
				# Use the alias'd echo from rc.subr
				echo -n "Mounting uzip image [$i]"
				sleep 0.2
			done
		done
	}&
	spinner_pid=$!
	trap kill_spinner SIGINT SIGTERM SIGHUP
	mdmfs -P -F /uzip/usr.local.uzip -oro md.uzip /usr/local
	kill ${spinner_pid}
	echo

	# Create and mount a writeable directory to /usr/local using
	# unionfs, so users can install packages.
	if (mount | grep -qE '/data '); then
		if [ ! -d /data/usr/local ]; then
			mkdir -p /data/usr/local
		fi
		mount -t unionfs -o rw,noatime /data/usr/local /usr/local
	fi
}

load_rc_config $name
run_rc_command "$1"

