#!/bin/sh -
#
# Copyright (c) 2021 The NomadBSD Project
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# PROVIDE: mount_enc_zfs
# REQUIRE: FILESYSTEMS
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="mount_enc_zfs"
desc="Prompt for ZFS passphrase and mount encrypted dataset"
rcvar="mount_enc_zfs_enable"
start_cmd="mount_enc_zfs_start"

load_rc_config $name

: ${mount_enc_zfs_enable:="NO"}

mount_enc_zfs_start()
{
	if [ -z "${mount_enc_zfs_dataset}" ]; then
		echo "mount_enc_zfs: mount_enc_zfs_dataset not defined" >&2
		return
	fi
	local status=$(zfs get -H keystatus "${mount_enc_zfs_dataset}")
	[ $? -ne 0 ] && return

	if (echo "${status}" | grep -w -q available); then
		return
	fi
	if [ -n "${keymap}" ]; then
		local ttydev=$(tty) || ttydev="/dev/console"
		local keymap=$(basename ${keymap} .kbd)
		local errmsg=$(kbdcontrol < ${ttydev} -l ${keymap} 2>&1)

		if [ -n "${errmsg}" ]; then
			echo "Warning: Failed to set keymap '${keymap}': ${errmsg}"
			echo "Take this into account when entering your ZFS password."
		fi
	fi
	zfs load-key -r "${mount_enc_zfs_dataset}" || return
	zfs mount "${mount_enc_zfs_dataset}"
}

run_rc_command "$1"
