#!/bin/sh

# PROVIDE: setup_netifs
# BEFORE: netif NETWORKING

. /etc/rc.subr

setup_netifs_enable=${setup_netifs_enable-"NO"}

name="setup_netifs"
rcvar="setup_netifs_enable"
load_rc_config $name
start_cmd="${name}_start"

setup_netifs_start() {
	rc_conf=/etc/rc.conf

	sed -E '/^# -- setup_netifs start --/,/^# -- setup_netifs end --$/d' \
		$rc_conf > /tmp/rc.conf.$$ && \
	mv /tmp/rc.conf.$$ $rc_conf
	ethernets=`ifconfig | awk '
	BEGIN {
		n = 0;
	}
	{
		if (/^[0-9a-zA-Z]+:/) {
			split($1, tmp, ":");
			if_name[n] = tmp[1];
		} else if (/^[ \t]+media: Ethernet*/)
			print if_name[n++];
	}'`
	wlans=`sysctl net.wlan.devices | awk -F"[: ]+" '{
		for (i = 2; i <= NF; i++)
			print $i;
	}'`

	printf "# -- setup_netifs start --\n" >> $rc_conf;
	n=0;
	for i in $wlans; do
		printf "wlans_%s=\"wlan%d\"\n" $i $n >> $rc_conf
		printf "ifconfig_wlan%d=\"up scan WPA DHCP\"\n" $n >> $rc_conf
		n=`expr $n + 1`;
	done
	n=0;
	for i in $ethernets; do
		printf "ifconfig_%s=\"DHCP\"\n" $i >> $rc_conf
		n=`expr $n + 1`
	done
	printf "# -- setup_netifs end --\n" >> $rc_conf
}

setup_netifs_start
load_rc_config $name
run_rc_command "$1"

