#!/bin/sh

# PROVIDE: setup_netifs
# REQUIRE: FILESYSTEMS
# BEFORE: netif

. /etc/rc.subr

setup_netifs_enable=${setup_netifs_enable-"NO"}

name="setup_netifs"
rcvar="setup_netifs_enable"
start_cmd="${name}_start"

setup_netifs_start() {
	mods=$(/usr/local/libexec/dsbdriverd -l 2>/dev/null | \
		awk -F ':+' '/[Ee]thernet|[Nn]etwork]/ { print $2 }')
	for m in ${mods}; do
		kldstat -v | grep -q -E "${m#if_}|$m" || kldload $m
	done
	mkdir /var/run/wpa_supplicant >/dev/null 2>&1

	ethernets=$(ifconfig | awk '
	BEGIN {
		n = 0;
	}
	{
		if (/^[0-9a-zA-Z]+:/) {
			split($1, tmp, ":");
			if_name[n] = tmp[1];
		} else if (/^[ \t]+media: Ethernet*/)
			print if_name[n++];
	}')

	wlans=$(sysctl net.wlan.devices | awk -F"[: ]+" '{
		for (i = 2; i <= NF; i++)
			print $i;
	}')

	n=0;
	for i in $wlans; do
		sysrc "wlans_${i}=wlan${n}"
		sysrc "ifconfig_wlan${n}=up scan WPA DHCP"
		n=$(($n + 1))
	done

	n=0;
	for i in $ethernets; do
		sysrc "ifconfig_${i}=DHCP"
		n=$(($n + 1))
	done
}

load_rc_config $name
run_rc_command "$1"

