#!/bin/sh
#
# Copyright (c) 2022, The NomadBSD Project
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# PROVIDE: zfs_prefetch_switch
# REQUIRE: zfs

. /etc/rc.subr

zfs_prefetch_switch_enable=${zfs_prefetch_switch_enable-"NO"}

name="zfs_prefetch_switch"
desc="Disables ZFS prefetch if the system has less than 4 GB of ram"
rcvar="${name}_enable"
start_cmd="${name}_start"

check_has_less_than_4gb_ram() {
	mem_bytes=$(sysctl -n hw.physmem)
	mem_gb=$((${mem_bytes} / 1000000000))
	[ ${mem_gb} -lt 4 ]
}

zfs_prefetch_switch_start() {
	# The default for vfs.zfs.prefetch_disable is 0
	check_has_less_than_4gb_ram && sysctl vfs.zfs.prefetch_disable=1
}

load_rc_config $name
run_rc_command "$1"

