// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b2f3e028-c6d9-4fc7-898b-fcf5ddcd80a9");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1572838328);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1572838403);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7308);
user_pref("browser.cache.disk.capacity", 327680);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.memory.capacity", -1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1572838299);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{00781a28-a8d1-4d20-baa7-1e2d98ad638e}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1572838400062");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1572840189062");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1572838307188");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1572841907188");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.interval", 1800000);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191102211034");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 12373);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191102211034");
user_pref("browser.startup.homepage_override.mstone", "68.2.0");
user_pref("browser.startup.lastColdStartupCheck", 1572838375);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1572838305159");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.2.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191102211034");
user_pref("extensions.lastAppVersion", "68.2.0");
user_pref("extensions.lastPlatformVersion", "68.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"675faa06-875d-474e-b764-7aaca7df9210\",\"fxmonitor@mozilla.org\":\"f121fdad-6bbc-4a1a-bba5-1287143cad50\",\"screenshots@mozilla.org\":\"7b7bf0c7-3be2-42b0-91d1-929210b2ef17\",\"webcompat-reporter@mozilla.org\":\"50ef7515-8992-4a58-a560-53eb64b2f374\",\"webcompat@mozilla.org\":\"c4b7a389-392a-4c4b-9802-fe998d89c431\",\"default-theme@mozilla.org\":\"e61828eb-efcd-469f-9c42-f21ece6e37a2\",\"google@search.mozilla.org\":\"249290b9-ead2-4d1c-b626-50c431c1e02d\",\"amazondotcom@search.mozilla.org\":\"ffdc6647-c4b4-44d5-9d8f-daaa6c706d5b\",\"bing@search.mozilla.org\":\"b120ed18-0339-4ae2-bc8f-e65bd4ad0a3d\",\"ddg@search.mozilla.org\":\"c33fa0b4-21eb-4fe0-87e3-1605a9fdf5de\",\"ebay@search.mozilla.org\":\"ef0d563e-8e72-4be5-9abe-f876cfe26689\",\"twitter@search.mozilla.org\":\"2f73d6dc-9811-4072-b4f1-b190d70a3406\",\"wikipedia@search.mozilla.org\":\"dd1e22fc-71b3-4499-a5c1-08a88fece16e\",\"uBlock0@raymondhill.net\":\"93a86a2b-678e-4f2f-9791-c7308e5d1dd4\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1572838372);
user_pref("toolkit.telemetry.cachedClientID", "85018c48-9ad0-4cf5-ac00-f1ba211d9819");
user_pref("toolkit.telemetry.previousBuildID", "20191102211034");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
