#!/bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct
export GIO_USE_VOLUME_MONITOR=unix

export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

create_cache_dir()
{
  local path="${HOME}/.cache"
  [ ! -L "${path}" ] && return
  local target=$(readlink "${path}")
  [ -d "${target}" ] && return
  mkdir -p "${target}"
}

if [ -f ~/.firstrun ]; then
  . ~/.firstrun
  rm -f ~/.firstrun
fi

create_cache_dir

. /usr/local/etc/xdg/xfce4/xinitrc

