// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "e04133ee-1c92-460f-9dc8-d3385e18331a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1583437424);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1583437536);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7596);
user_pref("browser.cache.disk.capacity", 409600);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.memory.capacity", -1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1583440994);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{98184f68-db1e-40de-82f8-9dd2ca5da8bf}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1583437542769");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1583439357769");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1583441003844");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1583444603844");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.interval", 1800000);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200222171321");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 6270);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200222171321");
user_pref("browser.startup.homepage_override.mstone", "68.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1583437508);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1583441001293");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200222171321");
user_pref("extensions.lastAppVersion", "68.5.0");
user_pref("extensions.lastPlatformVersion", "68.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bc391ea3-b963-448d-bfd3-d12c5f42f2ae\",\"fxmonitor@mozilla.org\":\"95cb4243-6b25-4a91-8f0d-a1020009aee2\",\"screenshots@mozilla.org\":\"46bc0f48-b5f4-413c-9674-35b2d5f32bec\",\"webcompat-reporter@mozilla.org\":\"86d06915-ccca-422e-a5a5-50afde8999e3\",\"webcompat@mozilla.org\":\"84cb4794-1e15-4ca3-bb7e-9d039ecd2222\",\"default-theme@mozilla.org\":\"d59789bf-660e-4274-be6f-92bec70e9744\",\"google@search.mozilla.org\":\"4b4ad6f7-bee8-4723-bea9-674f4b9563d6\",\"amazondotcom@search.mozilla.org\":\"39d941e9-6e4f-422f-8aa5-03ef96ccfdd6\",\"bing@search.mozilla.org\":\"31442cf2-b245-492c-9189-ef6b73815268\",\"ddg@search.mozilla.org\":\"df485887-c7fb-4cf4-928e-18f6838cf020\",\"ebay@search.mozilla.org\":\"0e6175ac-40c7-44f5-b567-3f2a327d10d5\",\"twitter@search.mozilla.org\":\"4b223704-0b07-4d61-8b5b-18d16609187a\",\"wikipedia@search.mozilla.org\":\"e7b5310a-1d2d-4aa1-a14e-9b1fb8b46884\",\"uBlock0@raymondhill.net\":\"60d68387-68e5-4b6b-96ba-58bbca1b2f53\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1583437505);
user_pref("toolkit.telemetry.cachedClientID", "e1ab574b-ff43-40ae-8b8a-ccd37a4c1c56");
user_pref("toolkit.telemetry.previousBuildID", "20200222171321");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
