// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "42ba11be-eb6d-453f-82ab-260120bd8666");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581067082);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1581067353);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1581067233);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7444);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.memory.capacity", -1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581067052);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{36c554b3-c923-427a-b57e-f88ef59046c2}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1581067097966");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1581068913966");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581067059127");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581070659127");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.interval", 1800000);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200127090417");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 3580);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200127090417");
user_pref("browser.startup.homepage_override.mstone", "68.4.2");
user_pref("browser.startup.lastColdStartupCheck", 1581067205);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581067058137");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.4.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200127090417");
user_pref("extensions.lastAppVersion", "68.4.2");
user_pref("extensions.lastPlatformVersion", "68.4.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"698012f2-a4e8-4b9d-898d-fd7d9d1a2aa3\",\"fxmonitor@mozilla.org\":\"6fef69d7-33f4-447e-9ff8-d659f09a678e\",\"screenshots@mozilla.org\":\"a1c2649c-3dd4-4630-b4cc-84ff138c4775\",\"webcompat-reporter@mozilla.org\":\"35990775-097d-4d07-87fd-85c72cd28ffb\",\"webcompat@mozilla.org\":\"9eae0c89-6433-4bf6-b155-d0abc927a9de\",\"default-theme@mozilla.org\":\"1e5fa185-fb19-4e29-918a-5da75b06f68e\",\"google@search.mozilla.org\":\"4a12bfe9-be43-492e-a07c-b7d7a8cc66d7\",\"amazondotcom@search.mozilla.org\":\"58e9f158-d4f9-4cdd-9290-5ced1a21bea9\",\"bing@search.mozilla.org\":\"571fe321-b26a-4673-a643-49b093f20378\",\"ddg@search.mozilla.org\":\"3685ff6a-f367-4329-88ea-5cc0cbffd769\",\"ebay@search.mozilla.org\":\"e13f1109-1c37-45f0-adb4-6a7ac302f9a4\",\"twitter@search.mozilla.org\":\"d87253f9-c662-46bf-815f-497ec5c0f1c3\",\"wikipedia@search.mozilla.org\":\"57203c11-764a-493a-87e9-54ae9464dcf4\",\"uBlock0@raymondhill.net\":\"645d4c22-5b64-426b-8fee-8812f2243159\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1581067202);
user_pref("toolkit.telemetry.cachedClientID", "5b701f83-9b88-4292-a666-48692129cab0");
user_pref("toolkit.telemetry.previousBuildID", "20200127090417");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
