#!/bin/sh

export LC_ALL=en_US.UTF-8
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
export QT_QPA_PLATFORMTHEME=gtk2
export GTK2_RC_FILES="/usr/share/nomadbsd-setup/gtkrc-2.0"
feh --bg-fill /usr/share/nomadbsd-setup/background.png
/usr/libexec/nomadbsd-setup-gui&
exec openbox-session

