// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.user_id", "e8ba0c15-c0ef-4842-8157-2acad142d69d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549813132);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549813252);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1549812535);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549812735);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549812629);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1549813012);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549813532);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 430080);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.memory.capacity", -1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1549812507);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7ec5dd89-f362-4dfc-b196-7da0b1e8ab9d}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google,amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1549753200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549812666808");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549814476808");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549812524330");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549816124330");
user_pref("browser.sessionstore.interval", 1800000);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190202120925");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20190202120925");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1549812523034");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "564da2c0650c49dea66cb0240887d33f");
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1549813133);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190202120925");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8cba3fa6-3b03-4ba5-bc78-0513278a2910}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"31663ff7-59aa-4105-a4dd-51c40df0b394\",\"screenshots@mozilla.org\":\"d988bbd4-f613-44ba-b796-0e7ba71f3105\",\"webcompat-reporter@mozilla.org\":\"646b5472-b9ed-4083-9cb1-1ef3425bf177\",\"webcompat@mozilla.org\":\"9e0d4a3f-83ee-4c3d-a798-a8a2c244640b\",\"uBlock0@raymondhill.net\":\"e3e0b73e-b1bd-4bc7-ba43-f9c343e75dc3\",\"fxmonitor@mozilla.org\":\"f44d5a94-3c2b-4c60-b487-4234c8591631\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190202120925");
user_pref("media.gmp-manager.lastCheck", 1549813009);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 10720);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.blocklist.addons.checked", 1549813152);
user_pref("services.blocklist.gfx.checked", 1549813152);
user_pref("services.blocklist.onecrl.checked", 1549813152);
user_pref("services.blocklist.pinning.checked", 1549813152);
user_pref("services.blocklist.plugins.checked", 1549813152);
user_pref("services.settings.clock_skew_seconds", -141);
user_pref("services.settings.last_update_seconds", 1549813152);
user_pref("services.settings.main.language-dictionaries.last_check", 1549813152);
user_pref("services.settings.main.onboarding.last_check", 1549813152);
user_pref("services.settings.main.sites-classification.last_check", 1549813152);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1549813501);
user_pref("toolkit.telemetry.cachedClientID", "be05ceac-d576-42e1-a825-247ffd7811c4");
user_pref("toolkit.telemetry.previousBuildID", "20190202120925");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
