// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "2c34ce54-91ca-46fd-ab58-f91901ac0cf7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1668000258);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1668000265);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1668000234);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{b8557937-9146-45a1-8e43-7ee8ded92a98}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1668000161);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f6a817a7-24a7-4dad-91cd-da1ab7361126}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1668000165);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1668000284255");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1668002061255");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1668000240029");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1668021840029");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.interval", 1800000);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221108220917");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20221108220917");
user_pref("browser.startup.homepage_override.mstone", "102.5.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_14\",\"url\":\"https://www.mozilla.org/firefox/welcome/14\",\"expire\":1668470400000}");
user_pref("browser.startup.lastColdStartupCheck", 1668000230);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1668000167638");
user_pref("distribution.iniFile.exists.appversion", "102.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "df30d8613eba41b4a517de7120d4575b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221108220917");
user_pref("extensions.lastAppVersion", "102.5.0");
user_pref("extensions.lastPlatformVersion", "102.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b3d27e7c-1c2f-4166-b636-45f10e40f269\",\"formautofill@mozilla.org\":\"ffa1dc60-91c1-440c-8fcf-85296be76b77\",\"pictureinpicture@mozilla.org\":\"dcdf66eb-af9d-46cf-a73f-688c2a44f045\",\"screenshots@mozilla.org\":\"402a78ce-a18c-4dc1-9abc-2c8691d18f8c\",\"webcompat-reporter@mozilla.org\":\"367a4cd0-2db7-40bb-ad98-aa21379d53fc\",\"webcompat@mozilla.org\":\"52a2435a-2478-499c-a2ea-d1ceb6fa3647\",\"default-theme@mozilla.org\":\"4f08155d-2ec0-4d91-8128-08d4d788fbc1\",\"addons-search-detection@mozilla.com\":\"05b32e0c-a137-4576-a1a8-58380e9a3847\",\"google@search.mozilla.org\":\"c5c4f755-fa9a-49c2-b8cd-a81d7b4662e5\",\"wikipedia@search.mozilla.org\":\"54d99a1c-97c7-40de-8e6f-6b32efafa9c9\",\"bing@search.mozilla.org\":\"a4fb4e89-b506-483c-80ca-1871cfb80d52\",\"amazon@search.mozilla.org\":\"fafdbbae-3a77-43a6-bdc0-a418be1f8b93\",\"ddg@search.mozilla.org\":\"53dd4f13-8f00-4745-9b87-f1ff7a8ac724\",\"uBlock0@raymondhill.net\":\"d8189d50-fc5f-4013-8be8-b78d71b04839\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1668000169);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("toolkit.startup.last_success", 1668000224);
user_pref("toolkit.telemetry.cachedClientID", "6b39c7de-62d8-4ad0-84e4-84517e5e8b97");
user_pref("toolkit.telemetry.previousBuildID", "20221108220917");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
